'use server'

// ── Pass 34: Public audit / business-registration server action ───
//
// This is the entry point invoked by the public /register-business form
// (and the /audit funnel). It now writes to `public.audit_submissions`
// — the intake queue — rather than directly to `business_audits`.
//
// Why the split:
//   • audit_submissions = raw public intake from the website.
//   • business_audits   = INTERNAL audit results generated by the
//                         Phase 26 deployment-score engine for an
//                         existing client business.
// The founder reviews submissions in /admin/audits and explicitly
// converts qualified leads into a real business + business_audits row
// later (a follow-up pass owns the conversion flow).
//
// SECURITY
//   • Identity is not trusted from the client — public posts are
//     anonymous by design. We use the service-role client to bypass
//     RLS for the insert. The service role key never reaches the
//     browser (see lib/supabase/server.ts).
//   • All fields are validated with Zod and length-capped before insert.
//   • Insert failures are surfaced as safe user-facing errors. We never
//     silently mark a failed submission as queued. We never return raw
//     Supabase error text to the user.
//   • Relevance AI is NOT triggered from this flow (Pass 34 scope). The
//     internal team is still notified server-side via notifyInternalTeam.

import { createServiceRoleClient } from '@/lib/supabase/server'
import { businessRegistrationSchema } from '@/lib/validation/registration'
import { notifyInternalTeam } from '@/lib/relevance/relevance-service'
import { sendAuditNotificationEmail } from '@/lib/email/audit-notification'

export interface RegistrationResult {
  ok:             boolean
  submission_id?: string
  error?:         string
}

export async function submitBusinessRegistration(
  formData: FormData,
): Promise<RegistrationResult> {
  // ── 1. Parse and validate ──────────────────────────────────────
  const raw = Object.fromEntries(formData.entries())

  // Multi-value fields come through as comma-separated strings from the
  // form; coerce them back into arrays so Zod can validate the shape.
  const parsed = businessRegistrationSchema.safeParse({
    ...raw,
    services:           splitCsv(raw.services as string | undefined),
    preferred_channels: splitCsv(raw.preferred_channels as string | undefined),
  })

  if (!parsed.success) {
    return { ok: false, error: parsed.error.errors[0]?.message ?? 'Invalid input.' }
  }
  const data = parsed.data

  // ── 2. Guard service-role availability ─────────────────────────
  if (!process.env.SUPABASE_SERVICE_ROLE_KEY) {
    console.error('[submitBusinessRegistration] SUPABASE_SERVICE_ROLE_KEY missing')
    return { ok: false, error: 'Server configuration error. Please try again later.' }
  }

  const db = createServiceRoleClient()

  // ── 3. Build the audit_submissions row ─────────────────────────
  // • Empty strings become null so DB queries on optional fields don't
  //   trip over '' vs null distinctions.
  // • Numeric form inputs (monthly_leads, team_size) are converted to
  //   text to match the audit_submissions schema.
  const submissionRow = {
    business_name:              data.business_name,
    contact_name:               nullIfEmpty(data.contact_name),
    email:                      nullIfEmpty(data.contact_email),
    phone:                      nullIfEmpty(data.phone),
    industry:                   nullIfEmpty(data.industry),
    business_type:              nullIfEmpty(data.business_type),
    location:                   nullIfEmpty(data.location),
    city:                       nullIfEmpty(data.city),
    country:                    nullIfEmpty(data.country),
    website:                    nullIfEmpty(data.website),
    instagram:                  nullIfEmpty(data.instagram),
    facebook:                   nullIfEmpty(data.facebook),
    whatsapp:                   nullIfEmpty(data.whatsapp),
    current_booking:            nullIfEmpty(data.current_booking),
    monthly_leads:              numToText(data.monthly_leads),
    biggest_problem:            nullIfEmpty(data.biggest_problem),
    services_offered:           data.services.length > 0 ? data.services.join(', ').slice(0, 2000) : null,
    business_hours:             nullIfEmpty(data.business_hours),
    team_size:                  numToText(data.team_size),
    existing_booking_software:  nullIfEmpty(data.existing_software),
    preferred_channels:         data.preferred_channels,
    selected_plan:              nullIfEmpty(data.selected_plan),
    source:                     'website',
    status:                     'new',
    priority:                   'normal',
    notes:                      nullIfEmpty(data.notes),
  }

  // ── 4. Insert ──────────────────────────────────────────────────
  const { data: inserted, error: insertErr } = await db
    .from('audit_submissions')
    .insert(submissionRow)
    .select('id')
    .single()

  if (insertErr || !inserted) {
    // Log full error server-side; return a safe message to the user.
    // Critically: we DO NOT pretend the submission was queued. Failure
    // is surfaced so the form can retry or the user can email support.
    console.error(
      '[submitBusinessRegistration] insert failed:',
      insertErr?.message,
      '| code:', insertErr?.code,
      '| details:', insertErr?.details,
    )

    const userMessage = isMissingTableError(insertErr)
      ? 'Audit intake is currently unavailable. Please try again in a few minutes — our team has been notified.'
      : 'We could not save your submission. Please try again, or email us at support@helios.ai.'

    return { ok: false, error: userMessage }
  }

  const submissionId = inserted.id as string

  // ── 5. Notify internal team (non-fatal) ────────────────────────
  try {
    await notifyInternalTeam({
      type:        'business_registered',
      business_id: submissionId,
      message:     `New audit submission: ${data.business_name}` +
        (data.industry  ? ` (${data.industry}` : '') +
        (data.city      ? `, ${data.city}`     : '') +
        (data.industry || data.city ? ')'      : '') +
        (data.selected_plan ? ` — requested ${data.selected_plan}` : ''),
    })
    await sendAuditNotificationEmail({
      submission_id:      submissionId,
      business_name:      data.business_name,
      contact_name:       nullIfEmpty(data.contact_name),
      contact_email:      nullIfEmpty(data.contact_email),
      industry:           nullIfEmpty(data.industry),
      city:               nullIfEmpty(data.city),
      country:            nullIfEmpty(data.country),
      website:            nullIfEmpty(data.website),
      biggest_problem:    nullIfEmpty(data.biggest_problem),
      monthly_leads:      typeof data.monthly_leads === 'number' ? data.monthly_leads : null,
      preferred_channels: data.preferred_channels,
    })
  } catch (notifyErr) {
    // Internal notification failures do not block the submission.
    console.error('[submitBusinessRegistration] notify failed:', notifyErr instanceof Error ? notifyErr.message : notifyErr)
  }

  return { ok: true, submission_id: submissionId }
}

// ── Helpers ───────────────────────────────────────────────────────

function splitCsv(raw: string | undefined): string[] {
  if (!raw) return []
  return raw.split(',').map((s) => s.trim()).filter(Boolean).slice(0, 50)
}

function nullIfEmpty(v: string | null | undefined): string | null {
  if (typeof v !== 'string') return null
  const t = v.trim()
  return t.length === 0 ? null : t
}

function numToText(v: number | null | undefined): string | null {
  if (typeof v !== 'number' || Number.isNaN(v)) return null
  return String(v)
}

// Detects PostgREST "relation does not exist" errors so we can show a
// friendlier message until the migration is applied in an environment.
interface PostgrestLikeError { message?: string; code?: string }
function isMissingTableError(e: PostgrestLikeError | null | undefined): boolean {
  if (!e) return false
  if (e.code === '42P01') return true
  const m = (e.message ?? '').toLowerCase()
  return m.includes('relation') && m.includes('does not exist')
}
