-- ════════════════════════════════════════════════════════════════════
-- Pass 34: audit_submissions table — public intake queue
-- ════════════════════════════════════════════════════════════════════
--
-- Purpose:
--   audit_submissions captures RAW public-form submissions from the
--   /audit and /register-business flows on the website. It is the
--   intake queue the founder reviews from /admin/audits.
--
--   This table is separate from `business_audits` (Phase 26) which
--   stores INTERNAL audit results generated by the deployment-score
--   engine for existing client businesses. The two tables are linked
--   by linked_business_id + linked_business_audit_id once the founder
--   converts a submission into a real client + audit.
--
-- Identity rules (must hold at all times):
--   • The submitter has no Supabase auth yet — public form posts go
--     through a server action that uses the service role to bypass RLS.
--   • Only founder_admin can SELECT, UPDATE, or DELETE submissions.
--   • Clients and other team roles have no visibility.
--   • is_founder_admin() (Pass 31, in migration 20260518120000) is the
--     authoritative role check.
--
-- Safety:
--   • Additive migration only. Re-runnable via IF NOT EXISTS guards.
--   • No existing tables are altered.
--   • business_audits remains the source of truth for generated audit
--     reports — this table never duplicates that content.
-- ════════════════════════════════════════════════════════════════════

-- ── 1. Extension ───────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ── 2. Table ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.audit_submissions (
  id                          uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Identity (from the form)
  business_name               text NOT NULL,
  contact_name                text,
  email                       text,
  phone                       text,
  industry                    text,
  business_type               text,
  location                    text,
  city                        text,
  country                     text,
  website                     text,
  instagram                   text,
  facebook                    text,
  whatsapp                    text,

  -- Operations questions
  current_booking             text,
  monthly_leads               text,
  biggest_problem             text,
  services_offered            text,
  business_hours              text,
  team_size                   text,
  existing_booking_software   text,
  preferred_channels          text[] NOT NULL DEFAULT '{}',
  selected_plan               text,

  -- Triage state
  source                      text NOT NULL DEFAULT 'website',
  status                      text NOT NULL DEFAULT 'new',
  priority                    text NOT NULL DEFAULT 'normal',
  qualification_score         integer,
  notes                       text,

  -- Link to converted records (populated when the founder accepts the lead)
  linked_business_id          uuid,
  linked_business_audit_id    uuid,

  created_at                  timestamptz NOT NULL DEFAULT now(),
  updated_at                  timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT audit_submissions_status_check CHECK (status IN (
    'new', 'in_review', 'qualified', 'contacted', 'converted', 'archived'
  )),
  CONSTRAINT audit_submissions_priority_check CHECK (priority IN (
    'low', 'normal', 'high', 'urgent'
  )),
  CONSTRAINT audit_submissions_qualification_score_check CHECK (
    qualification_score IS NULL
    OR (qualification_score >= 0 AND qualification_score <= 100)
  )
);

COMMENT ON TABLE  public.audit_submissions IS 'Public-form audit / business-registration intake. Reviewed by founder_admin via /admin/audits.';
COMMENT ON COLUMN public.audit_submissions.source     IS 'website | imported | manual';
COMMENT ON COLUMN public.audit_submissions.status     IS 'new | in_review | qualified | contacted | converted | archived';
COMMENT ON COLUMN public.audit_submissions.priority   IS 'low | normal | high | urgent';
COMMENT ON COLUMN public.audit_submissions.linked_business_id       IS 'Set when the founder converts this submission into an active client.';
COMMENT ON COLUMN public.audit_submissions.linked_business_audit_id IS 'Set when the converted client has an internal business_audits row generated.';

-- ── 3. Indexes ─────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS audit_submissions_created_at_idx
  ON public.audit_submissions (created_at DESC);
CREATE INDEX IF NOT EXISTS audit_submissions_status_idx
  ON public.audit_submissions (status);
CREATE INDEX IF NOT EXISTS audit_submissions_email_idx
  ON public.audit_submissions (lower(email));
CREATE INDEX IF NOT EXISTS audit_submissions_selected_plan_idx
  ON public.audit_submissions (selected_plan);
CREATE INDEX IF NOT EXISTS audit_submissions_priority_idx
  ON public.audit_submissions (priority);

-- ── 4. updated_at trigger ──────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.audit_submissions_set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS audit_submissions_set_updated_at ON public.audit_submissions;
CREATE TRIGGER audit_submissions_set_updated_at
  BEFORE UPDATE ON public.audit_submissions
  FOR EACH ROW EXECUTE FUNCTION public.audit_submissions_set_updated_at();

-- ── 5. Row Level Security ──────────────────────────────────────────
ALTER TABLE public.audit_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_submissions FORCE  ROW LEVEL SECURITY;

-- Reset any pre-existing policies (idempotent re-apply).
DROP POLICY IF EXISTS audit_submissions_select_founder_admin ON public.audit_submissions;
DROP POLICY IF EXISTS audit_submissions_insert_founder_admin ON public.audit_submissions;
DROP POLICY IF EXISTS audit_submissions_update_founder_admin ON public.audit_submissions;
DROP POLICY IF EXISTS audit_submissions_delete_founder_admin ON public.audit_submissions;

-- SELECT: founder_admin only. Clients, team roles, and anon are blocked.
-- The is_founder_admin() helper was created in 20260518120000.
CREATE POLICY audit_submissions_select_founder_admin
  ON public.audit_submissions
  FOR SELECT
  TO authenticated
  USING (public.is_founder_admin());

-- INSERT/UPDATE/DELETE: only founder_admin via authenticated client.
-- Anonymous public form posts go through the server-side action
-- (`submitBusinessRegistration` in lib/actions/registration.ts) which
-- uses the service-role client to bypass RLS. The service role key
-- never reaches the browser (see lib/supabase/server.ts).
CREATE POLICY audit_submissions_insert_founder_admin
  ON public.audit_submissions
  FOR INSERT
  TO authenticated
  WITH CHECK (public.is_founder_admin());

CREATE POLICY audit_submissions_update_founder_admin
  ON public.audit_submissions
  FOR UPDATE
  TO authenticated
  USING      (public.is_founder_admin())
  WITH CHECK (public.is_founder_admin());

CREATE POLICY audit_submissions_delete_founder_admin
  ON public.audit_submissions
  FOR DELETE
  TO authenticated
  USING (public.is_founder_admin());

-- ── 6. Access matrix ───────────────────────────────────────────────
--
-- After this migration:
--
--   anon                              → 0 read, 0 direct write
--   authenticated, not founder        → 0 read, 0 write
--   authenticated, founder_admin      → full SELECT/INSERT/UPDATE/DELETE
--   service_role                      → bypasses RLS (used by the
--                                       public registration server action)
